// Implementation file for parser generated by fsyacc
module Parser
#nowarn "64";; // turn off warnings that type variables used in production annotations are instantiated to concrete type
open Microsoft.FSharp.Text.Lexing
open Microsoft.FSharp.Text.Parsing.ParseHelpers
# 1 "C:\Users\AIFU\Projects\SchizoFs\Parser.fsy"

//
// Schizo F# Referemce Compiler
// Copyright (C) 2014-2015  Wael El Oraiby
// 
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
// 
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.
//
open Ast
open System

# 28 "C:\Users\AIFU\Projects\SchizoFs\Parser.fs"
// This type is the type of tokens accepted by the parser
type token = 
  | EOF
  | SC of (TokenData)
  | RIGHT_HASH of (TokenData)
  | LEFT_HASH of (TokenData)
  | RIGHT_PAREN of (TokenData)
  | LEFT_PAREN of (TokenData)
  | RIGHT_BRACK of (TokenData)
  | LEFT_BRACK of (TokenData)
  | RIGHT_BRACE of (TokenData)
  | LEFT_BRACE of (TokenData)
  | FALSE of (Node)
  | TRUE of (Node)
  | TAG of (Node)
  | SYMBOL of (Node)
  | STRING of (Node)
  | REAL64 of (Node)
  | INT64 of (Node)
// This type is used to give symbolic names to token indexes, useful for error messages
type tokenId = 
    | TOKEN_EOF
    | TOKEN_SC
    | TOKEN_RIGHT_HASH
    | TOKEN_LEFT_HASH
    | TOKEN_RIGHT_PAREN
    | TOKEN_LEFT_PAREN
    | TOKEN_RIGHT_BRACK
    | TOKEN_LEFT_BRACK
    | TOKEN_RIGHT_BRACE
    | TOKEN_LEFT_BRACE
    | TOKEN_FALSE
    | TOKEN_TRUE
    | TOKEN_TAG
    | TOKEN_SYMBOL
    | TOKEN_STRING
    | TOKEN_REAL64
    | TOKEN_INT64
    | TOKEN_end_of_input
    | TOKEN_error
// This type is used to give symbolic names to token indexes, useful for error messages
type nonTerminalId = 
    | NONTERM__startstart
    | NONTERM_start
    | NONTERM_prog
    | NONTERM_atom
    | NONTERM_exp
    | NONTERM_exp_member
    | NONTERM_exp_member_list
    | NONTERM_exp_list
    | NONTERM_paren_exp
    | NONTERM_sc
    | NONTERM_bexp_list
    | NONTERM_brace_exp

// This function maps tokens to integers indexes
let tagOfToken (t:token) = 
  match t with
  | EOF  -> 0 
  | SC _ -> 1 
  | RIGHT_HASH _ -> 2 
  | LEFT_HASH _ -> 3 
  | RIGHT_PAREN _ -> 4 
  | LEFT_PAREN _ -> 5 
  | RIGHT_BRACK _ -> 6 
  | LEFT_BRACK _ -> 7 
  | RIGHT_BRACE _ -> 8 
  | LEFT_BRACE _ -> 9 
  | FALSE _ -> 10 
  | TRUE _ -> 11 
  | TAG _ -> 12 
  | SYMBOL _ -> 13 
  | STRING _ -> 14 
  | REAL64 _ -> 15 
  | INT64 _ -> 16 

// This function maps integers indexes to symbolic token ids
let tokenTagToTokenId (tokenIdx:int) = 
  match tokenIdx with
  | 0 -> TOKEN_EOF 
  | 1 -> TOKEN_SC 
  | 2 -> TOKEN_RIGHT_HASH 
  | 3 -> TOKEN_LEFT_HASH 
  | 4 -> TOKEN_RIGHT_PAREN 
  | 5 -> TOKEN_LEFT_PAREN 
  | 6 -> TOKEN_RIGHT_BRACK 
  | 7 -> TOKEN_LEFT_BRACK 
  | 8 -> TOKEN_RIGHT_BRACE 
  | 9 -> TOKEN_LEFT_BRACE 
  | 10 -> TOKEN_FALSE 
  | 11 -> TOKEN_TRUE 
  | 12 -> TOKEN_TAG 
  | 13 -> TOKEN_SYMBOL 
  | 14 -> TOKEN_STRING 
  | 15 -> TOKEN_REAL64 
  | 16 -> TOKEN_INT64 
  | 19 -> TOKEN_end_of_input
  | 17 -> TOKEN_error
  | _ -> failwith "tokenTagToTokenId: bad token"

/// This function maps production indexes returned in syntax errors to strings representing the non terminal that would be produced by that production
let prodIdxToNonTerminal (prodIdx:int) = 
  match prodIdx with
    | 0 -> NONTERM__startstart 
    | 1 -> NONTERM_start 
    | 2 -> NONTERM_prog 
    | 3 -> NONTERM_prog 
    | 4 -> NONTERM_atom 
    | 5 -> NONTERM_atom 
    | 6 -> NONTERM_atom 
    | 7 -> NONTERM_atom 
    | 8 -> NONTERM_atom 
    | 9 -> NONTERM_atom 
    | 10 -> NONTERM_exp 
    | 11 -> NONTERM_exp 
    | 12 -> NONTERM_exp_member 
    | 13 -> NONTERM_exp_member 
    | 14 -> NONTERM_exp_member_list 
    | 15 -> NONTERM_exp_member_list 
    | 16 -> NONTERM_exp_list 
    | 17 -> NONTERM_exp_list 
    | 18 -> NONTERM_paren_exp 
    | 19 -> NONTERM_paren_exp 
    | 20 -> NONTERM_sc 
    | 21 -> NONTERM_sc 
    | 22 -> NONTERM_bexp_list 
    | 23 -> NONTERM_bexp_list 
    | 24 -> NONTERM_brace_exp 
    | 25 -> NONTERM_brace_exp 
    | 26 -> NONTERM_brace_exp 
    | _ -> failwith "prodIdxToNonTerminal: bad production index"

let _fsyacc_endOfInputTag = 19 
let _fsyacc_tagOfErrorTerminal = 17

// This function gets the name of a token as a string
let token_to_string (t:token) = 
  match t with 
  | EOF  -> "EOF" 
  | SC _ -> "SC" 
  | RIGHT_HASH _ -> "RIGHT_HASH" 
  | LEFT_HASH _ -> "LEFT_HASH" 
  | RIGHT_PAREN _ -> "RIGHT_PAREN" 
  | LEFT_PAREN _ -> "LEFT_PAREN" 
  | RIGHT_BRACK _ -> "RIGHT_BRACK" 
  | LEFT_BRACK _ -> "LEFT_BRACK" 
  | RIGHT_BRACE _ -> "RIGHT_BRACE" 
  | LEFT_BRACE _ -> "LEFT_BRACE" 
  | FALSE _ -> "FALSE" 
  | TRUE _ -> "TRUE" 
  | TAG _ -> "TAG" 
  | SYMBOL _ -> "SYMBOL" 
  | STRING _ -> "STRING" 
  | REAL64 _ -> "REAL64" 
  | INT64 _ -> "INT64" 

// This function gets the data carried by a token as an object
let _fsyacc_dataOfToken (t:token) = 
  match t with 
  | EOF  -> (null : System.Object) 
  | SC _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
  | RIGHT_HASH _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
  | LEFT_HASH _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
  | RIGHT_PAREN _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
  | LEFT_PAREN _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
  | RIGHT_BRACK _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
  | LEFT_BRACK _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
  | RIGHT_BRACE _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
  | LEFT_BRACE _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
  | FALSE _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
  | TRUE _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
  | TAG _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
  | SYMBOL _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
  | STRING _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
  | REAL64 _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
  | INT64 _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
let _fsyacc_gotos = [| 0us; 65535us; 1us; 65535us; 0us; 1us; 1us; 65535us; 0us; 2us; 6us; 65535us; 16us; 13us; 17us; 13us; 18us; 13us; 20us; 13us; 24us; 13us; 27us; 13us; 7us; 65535us; 0us; 4us; 16us; 14us; 17us; 14us; 18us; 14us; 20us; 14us; 24us; 14us; 27us; 14us; 6us; 65535us; 16us; 19us; 17us; 19us; 18us; 19us; 20us; 15us; 24us; 15us; 27us; 15us; 3us; 65535us; 20us; 16us; 24us; 18us; 27us; 17us; 1us; 65535us; 20us; 21us; 7us; 65535us; 0us; 11us; 16us; 11us; 17us; 11us; 18us; 11us; 20us; 11us; 24us; 11us; 27us; 11us; 1us; 65535us; 26us; 24us; 1us; 65535us; 27us; 26us; 7us; 65535us; 0us; 12us; 16us; 12us; 17us; 12us; 18us; 12us; 20us; 12us; 24us; 12us; 27us; 12us; |]
let _fsyacc_sparseGotoTableRowOffsets = [|0us; 1us; 3us; 5us; 12us; 20us; 27us; 31us; 33us; 41us; 43us; 45us; |]
let _fsyacc_stateToProdIdxsTableElements = [| 1us; 0us; 1us; 0us; 1us; 1us; 1us; 2us; 1us; 3us; 1us; 4us; 1us; 5us; 1us; 6us; 1us; 7us; 1us; 8us; 1us; 9us; 1us; 10us; 1us; 11us; 1us; 12us; 1us; 13us; 1us; 14us; 2us; 15us; 17us; 2us; 15us; 22us; 2us; 15us; 23us; 1us; 15us; 2us; 18us; 19us; 2us; 18us; 19us; 1us; 19us; 1us; 20us; 3us; 21us; 23us; 26us; 1us; 21us; 4us; 23us; 24us; 25us; 26us; 3us; 24us; 25us; 26us; 1us; 25us; 1us; 26us; |]
let _fsyacc_stateToProdIdxsTableRowOffsets = [|0us; 2us; 4us; 6us; 8us; 10us; 12us; 14us; 16us; 18us; 20us; 22us; 24us; 26us; 28us; 30us; 32us; 35us; 38us; 41us; 43us; 46us; 49us; 51us; 53us; 57us; 59us; 64us; 68us; 70us; |]
let _fsyacc_action_rows = 30
let _fsyacc_actionTableElements = [|3us; 32768us; 0us; 3us; 5us; 20us; 9us; 27us; 0us; 49152us; 0us; 16385us; 0us; 16386us; 0us; 16387us; 0us; 16388us; 0us; 16389us; 0us; 16390us; 0us; 16391us; 0us; 16392us; 0us; 16393us; 0us; 16394us; 0us; 16395us; 0us; 16396us; 0us; 16397us; 0us; 16398us; 8us; 16401us; 5us; 20us; 9us; 27us; 10us; 10us; 11us; 9us; 13us; 5us; 14us; 6us; 15us; 8us; 16us; 7us; 8us; 16406us; 5us; 20us; 9us; 27us; 10us; 10us; 11us; 9us; 13us; 5us; 14us; 6us; 15us; 8us; 16us; 7us; 8us; 16407us; 5us; 20us; 9us; 27us; 10us; 10us; 11us; 9us; 13us; 5us; 14us; 6us; 15us; 8us; 16us; 7us; 0us; 16399us; 8us; 16400us; 5us; 20us; 9us; 27us; 10us; 10us; 11us; 9us; 13us; 5us; 14us; 6us; 15us; 8us; 16us; 7us; 1us; 16402us; 4us; 22us; 0us; 16403us; 0us; 16404us; 10us; 32768us; 1us; 25us; 5us; 20us; 8us; 29us; 9us; 27us; 10us; 10us; 11us; 9us; 13us; 5us; 14us; 6us; 15us; 8us; 16us; 7us; 0us; 16405us; 2us; 16408us; 1us; 23us; 8us; 28us; 8us; 32768us; 5us; 20us; 9us; 27us; 10us; 10us; 11us; 9us; 13us; 5us; 14us; 6us; 15us; 8us; 16us; 7us; 0us; 16409us; 0us; 16410us; |]
let _fsyacc_actionTableRowOffsets = [|0us; 4us; 5us; 6us; 7us; 8us; 9us; 10us; 11us; 12us; 13us; 14us; 15us; 16us; 17us; 18us; 19us; 28us; 37us; 46us; 47us; 56us; 58us; 59us; 60us; 71us; 72us; 75us; 84us; 85us; |]
let _fsyacc_reductionSymbolCounts = [|1us; 1us; 1us; 1us; 1us; 1us; 1us; 1us; 1us; 1us; 1us; 1us; 1us; 1us; 1us; 2us; 0us; 1us; 2us; 3us; 1us; 2us; 1us; 3us; 2us; 3us; 4us; |]
let _fsyacc_productionToNonTerminalTable = [|0us; 1us; 2us; 2us; 3us; 3us; 3us; 3us; 3us; 3us; 4us; 4us; 5us; 5us; 6us; 6us; 7us; 7us; 8us; 8us; 9us; 9us; 10us; 10us; 11us; 11us; 11us; |]
let _fsyacc_immediateActions = [|65535us; 49152us; 16385us; 16386us; 16387us; 16388us; 16389us; 16390us; 16391us; 16392us; 16393us; 16394us; 16395us; 16396us; 16397us; 16398us; 65535us; 65535us; 65535us; 16399us; 65535us; 65535us; 16403us; 16404us; 65535us; 16405us; 65535us; 65535us; 16409us; 16410us; |]
let _fsyacc_reductions ()  =    [| 
# 216 "C:\Users\AIFU\Projects\SchizoFs\Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : Node option)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
                      raise (Microsoft.FSharp.Text.Parsing.Accept(Microsoft.FSharp.Core.Operators.box _1))
                   )
                 : '_startstart));
# 225 "C:\Users\AIFU\Projects\SchizoFs\Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'prog)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 46 "C:\Users\AIFU\Projects\SchizoFs\Parser.fsy"
                                                                   _1 
                   )
# 46 "C:\Users\AIFU\Projects\SchizoFs\Parser.fsy"
                 : Node option));
# 236 "C:\Users\AIFU\Projects\SchizoFs\Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 49 "C:\Users\AIFU\Projects\SchizoFs\Parser.fsy"
                                                                   None 
                   )
# 49 "C:\Users\AIFU\Projects\SchizoFs\Parser.fsy"
                 : 'prog));
# 246 "C:\Users\AIFU\Projects\SchizoFs\Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'exp)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 50 "C:\Users\AIFU\Projects\SchizoFs\Parser.fsy"
                                                                   Some _1 
                   )
# 50 "C:\Users\AIFU\Projects\SchizoFs\Parser.fsy"
                 : 'prog));
# 257 "C:\Users\AIFU\Projects\SchizoFs\Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : Node)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 53 "C:\Users\AIFU\Projects\SchizoFs\Parser.fsy"
                                                                   _1 
                   )
# 53 "C:\Users\AIFU\Projects\SchizoFs\Parser.fsy"
                 : 'atom));
# 268 "C:\Users\AIFU\Projects\SchizoFs\Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : Node)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 54 "C:\Users\AIFU\Projects\SchizoFs\Parser.fsy"
                                                                   _1 
                   )
# 54 "C:\Users\AIFU\Projects\SchizoFs\Parser.fsy"
                 : 'atom));
# 279 "C:\Users\AIFU\Projects\SchizoFs\Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : Node)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 55 "C:\Users\AIFU\Projects\SchizoFs\Parser.fsy"
                                                                   _1 
                   )
# 55 "C:\Users\AIFU\Projects\SchizoFs\Parser.fsy"
                 : 'atom));
# 290 "C:\Users\AIFU\Projects\SchizoFs\Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : Node)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 56 "C:\Users\AIFU\Projects\SchizoFs\Parser.fsy"
                                                                   _1 
                   )
# 56 "C:\Users\AIFU\Projects\SchizoFs\Parser.fsy"
                 : 'atom));
# 301 "C:\Users\AIFU\Projects\SchizoFs\Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : Node)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 57 "C:\Users\AIFU\Projects\SchizoFs\Parser.fsy"
                                                                   _1 
                   )
# 57 "C:\Users\AIFU\Projects\SchizoFs\Parser.fsy"
                 : 'atom));
# 312 "C:\Users\AIFU\Projects\SchizoFs\Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : Node)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 58 "C:\Users\AIFU\Projects\SchizoFs\Parser.fsy"
                                                                   _1 
                   )
# 58 "C:\Users\AIFU\Projects\SchizoFs\Parser.fsy"
                 : 'atom));
# 323 "C:\Users\AIFU\Projects\SchizoFs\Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'paren_exp)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 61 "C:\Users\AIFU\Projects\SchizoFs\Parser.fsy"
                                                                   _1 
                   )
# 61 "C:\Users\AIFU\Projects\SchizoFs\Parser.fsy"
                 : 'exp));
# 334 "C:\Users\AIFU\Projects\SchizoFs\Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'brace_exp)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 62 "C:\Users\AIFU\Projects\SchizoFs\Parser.fsy"
                                                                   _1 
                   )
# 62 "C:\Users\AIFU\Projects\SchizoFs\Parser.fsy"
                 : 'exp));
# 345 "C:\Users\AIFU\Projects\SchizoFs\Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'atom)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 65 "C:\Users\AIFU\Projects\SchizoFs\Parser.fsy"
                                                                   _1 
                   )
# 65 "C:\Users\AIFU\Projects\SchizoFs\Parser.fsy"
                 : 'exp_member));
# 356 "C:\Users\AIFU\Projects\SchizoFs\Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'exp)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 66 "C:\Users\AIFU\Projects\SchizoFs\Parser.fsy"
                                                                   _1 
                   )
# 66 "C:\Users\AIFU\Projects\SchizoFs\Parser.fsy"
                 : 'exp_member));
# 367 "C:\Users\AIFU\Projects\SchizoFs\Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'exp_member)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 69 "C:\Users\AIFU\Projects\SchizoFs\Parser.fsy"
                                                                   [ _1 ] 
                   )
# 69 "C:\Users\AIFU\Projects\SchizoFs\Parser.fsy"
                 : 'exp_member_list));
# 378 "C:\Users\AIFU\Projects\SchizoFs\Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'exp_member_list)) in
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : 'exp_member)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 70 "C:\Users\AIFU\Projects\SchizoFs\Parser.fsy"
                                                                   _2 :: _1 
                   )
# 70 "C:\Users\AIFU\Projects\SchizoFs\Parser.fsy"
                 : 'exp_member_list));
# 390 "C:\Users\AIFU\Projects\SchizoFs\Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 73 "C:\Users\AIFU\Projects\SchizoFs\Parser.fsy"
                                                                   [] 
                   )
# 73 "C:\Users\AIFU\Projects\SchizoFs\Parser.fsy"
                 : 'exp_list));
# 400 "C:\Users\AIFU\Projects\SchizoFs\Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'exp_member_list)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 74 "C:\Users\AIFU\Projects\SchizoFs\Parser.fsy"
                                                                   _1 
                   )
# 74 "C:\Users\AIFU\Projects\SchizoFs\Parser.fsy"
                 : 'exp_list));
# 411 "C:\Users\AIFU\Projects\SchizoFs\Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : TokenData)) in
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : 'exp_list)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 77 "C:\Users\AIFU\Projects\SchizoFs\Parser.fsy"
                                                                   raise (Exception (sprintf "SyntaxError: Unmatched '(' @ Line: %d Column: %d" (_1.LineNumber + 1) (_1.Column + 1))) 
                   )
# 77 "C:\Users\AIFU\Projects\SchizoFs\Parser.fsy"
                 : 'paren_exp));
# 423 "C:\Users\AIFU\Projects\SchizoFs\Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : TokenData)) in
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : 'exp_list)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : TokenData)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 78 "C:\Users\AIFU\Projects\SchizoFs\Parser.fsy"
                                                                   match _2 with
                                                                   | [] -> Node.Unit _1
                                                                   | _  -> ListNode ((List.rev _2), _1) 
                   )
# 78 "C:\Users\AIFU\Projects\SchizoFs\Parser.fsy"
                 : 'paren_exp));
# 438 "C:\Users\AIFU\Projects\SchizoFs\Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : TokenData)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 83 "C:\Users\AIFU\Projects\SchizoFs\Parser.fsy"
                                                                  
                   )
# 83 "C:\Users\AIFU\Projects\SchizoFs\Parser.fsy"
                 : 'sc));
# 449 "C:\Users\AIFU\Projects\SchizoFs\Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'sc)) in
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : TokenData)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 84 "C:\Users\AIFU\Projects\SchizoFs\Parser.fsy"
                                                                  
                   )
# 84 "C:\Users\AIFU\Projects\SchizoFs\Parser.fsy"
                 : 'sc));
# 461 "C:\Users\AIFU\Projects\SchizoFs\Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'exp_member_list)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 87 "C:\Users\AIFU\Projects\SchizoFs\Parser.fsy"
                                                                   [ ListNode ((List.rev _1), TokenData.Empty) ] 
                   )
# 87 "C:\Users\AIFU\Projects\SchizoFs\Parser.fsy"
                 : 'bexp_list));
# 472 "C:\Users\AIFU\Projects\SchizoFs\Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'bexp_list)) in
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : 'sc)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'exp_member_list)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 88 "C:\Users\AIFU\Projects\SchizoFs\Parser.fsy"
                                                                   ( ListNode ((List.rev _3), TokenData.Empty) ) :: _1 
                   )
# 88 "C:\Users\AIFU\Projects\SchizoFs\Parser.fsy"
                 : 'bexp_list));
# 485 "C:\Users\AIFU\Projects\SchizoFs\Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : TokenData)) in
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : 'bexp_list)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 92 "C:\Users\AIFU\Projects\SchizoFs\Parser.fsy"
                                                                   raise (Exception (sprintf "SyntaxError: Unmatched '{' @ Line: %d Column: %d" (_1.LineNumber + 1) (_1.Column + 1))) 
                   )
# 92 "C:\Users\AIFU\Projects\SchizoFs\Parser.fsy"
                 : 'brace_exp));
# 497 "C:\Users\AIFU\Projects\SchizoFs\Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : TokenData)) in
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : 'bexp_list)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : TokenData)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 93 "C:\Users\AIFU\Projects\SchizoFs\Parser.fsy"
                                                                   ListNode ((List.rev _2), _1) 
                   )
# 93 "C:\Users\AIFU\Projects\SchizoFs\Parser.fsy"
                 : 'brace_exp));
# 510 "C:\Users\AIFU\Projects\SchizoFs\Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : TokenData)) in
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : 'bexp_list)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'sc)) in
            let _4 = (let data = parseState.GetInput(4) in (Microsoft.FSharp.Core.Operators.unbox data : TokenData)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 94 "C:\Users\AIFU\Projects\SchizoFs\Parser.fsy"
                                                                   ListNode ((List.rev _2), _1) 
                   )
# 94 "C:\Users\AIFU\Projects\SchizoFs\Parser.fsy"
                 : 'brace_exp));
|]
# 525 "C:\Users\AIFU\Projects\SchizoFs\Parser.fs"
let tables () : Microsoft.FSharp.Text.Parsing.Tables<_> = 
  { reductions= _fsyacc_reductions ();
    endOfInputTag = _fsyacc_endOfInputTag;
    tagOfToken = tagOfToken;
    dataOfToken = _fsyacc_dataOfToken; 
    actionTableElements = _fsyacc_actionTableElements;
    actionTableRowOffsets = _fsyacc_actionTableRowOffsets;
    stateToProdIdxsTableElements = _fsyacc_stateToProdIdxsTableElements;
    stateToProdIdxsTableRowOffsets = _fsyacc_stateToProdIdxsTableRowOffsets;
    reductionSymbolCounts = _fsyacc_reductionSymbolCounts;
    immediateActions = _fsyacc_immediateActions;
    gotos = _fsyacc_gotos;
    sparseGotoTableRowOffsets = _fsyacc_sparseGotoTableRowOffsets;
    tagOfErrorTerminal = _fsyacc_tagOfErrorTerminal;
    parseError = (fun (ctxt:Microsoft.FSharp.Text.Parsing.ParseErrorContext<_>) -> 
                              match parse_error_rich with 
                              | Some f -> f ctxt
                              | None -> parse_error ctxt.Message);
    numTerminals = 20;
    productionToNonTerminalTable = _fsyacc_productionToNonTerminalTable  }
let engine lexer lexbuf startState = (tables ()).Interpret(lexer, lexbuf, startState)
let start lexer lexbuf : Node option =
    Microsoft.FSharp.Core.Operators.unbox ((tables ()).Interpret(lexer, lexbuf, 0))
